### ISSUE TITLE
Feature Request - Translate packet values to meaningful strings according to VSIS

### ISSUE THREAD

**Issue by robertvanv** [dyster/IPTComShark#1]
In the VSIS packets, could you implement what the raw values translate into in a string value according to the VSIS. My recommendation would be to put this in a new column in the packet view while also keeping the current "Comment" column as the generic value description.

Example:
In EVC-8, the MMI_Q_TEXT value of 516 would show "Brake Test in Progress" in a separate column to "Predefined text message"

**Comment by robertvanv** [comment]
Most useful packets to implement would be:

EVC 8, 30, 101, and 152

**Comment by dyster** [comment]
Variable lookup tables have been added to suggested telegrams,
fixed by commit
[ae4dddacde2edf772a22f240e21f3cd98acf3102](https://github.com/dyster/sonesson-tools/commit/ae4dddacde2edf772a22f240e21f3cd98acf3102)
in sonesson-tools
