### ISSUE TITLE
Changes to default layout for increased useability

### ISSUE THREAD

**Issue by robertvanv** [dyster/IPTComShark#12]
The "Protocol" and "Protocol Info" columns are usually not needed for fault analysis/log review. Could you provide means to hide these in the default view? Or maybe implement a settings file where you can select the default columns to be displayed?

Also, this extends to the "Type" column in the message detail window.
#Enhancement

**Comment by dyster** [comment]
Columns can now be reordered, and column order, width and visibility will be saved

**Comment by dyster** [comment]
right click on a column and untick to hide
