### ISSUE TITLE
 IPTComShark sometimes fails to display EVC-11 (MMI_CURRENT_SR_RULES)

### ISSUE THREAD

**Issue by pnfawcett** [dyster/IPTComShark#35]
IPTComShark sometimes fails to interpret EVC-11 messages correctly. This seems to occur when the screen is opened for the first time. When the message is returned for validation of individual fields the message is processed correctly.

**Comment by robertvanv** [comment]
This has been fixed by my EVC-11 migration to the new format. I have already verified the packet works with MMI_N_DATA_ELEMENTS = 0.

**Comment by dyster** [comment]
closing based on robertvanv comment
