### ISSUE TITLE
Incorrectly parsing UInt8 with less than 8 bits

### ISSUE THREAD

**Issue by robertvanv** [dyster/IPTComShark#37]
Currently, if the UInt8 Bitfield type is used, the value gets shifted/padded if the number of bits are less than 8. This affects the output value.

Quick test seems to show that FieldGetter function used in the BitStreamParser might fix the issue. I have NOT tested all cases though.

P.S. Uint64 should probably be named UInt64, in order to be consistent

**Comment by dyster** [comment]
Fixed upstream in sonesson-tools

**Comment by robertvanv** [comment]
Just curious to know where/how is it fixed upstream in sonesson-tools? I didn't see any changes in the BitStreamParser.cs file?
Am I missing something?
