### ISSUE TITLE
EVC-18 packet not being parsed

### ISSUE THREAD

**Issue by robertvanv** [dyster/IPTComShark#6]
Currently, EVC-18 packets are not being parsed correctly and hence do not come up in packet view.

This might also extend to other VBC related data packets (EVC-19, 28, 29, 118, 119, 128, and 129), but this is not confirmed.

**Comment by dyster** [comment]
Closed by commit
https://github.com/dyster/sonesson-tools/commit/efe560958bbbbee526f55e2d5894a1a63f13c039
in sonesson-tools
