### ISSUE TITLE
Unable to filter on all packet types

### ISSUE THREAD

**Issue by robertvanv** [dyster/IPTComShark#7]
The filtering by packet types within the column header "Name" does not offer all packets found within the file. The notable ones missing are EVC-0, EVC-4, EVC-8, and EVC-30. I believe more options are missing, but these are just a start.

**Comment by dyster** [comment]
The built in column filtering that comes with the listview only looks at the first 10000 columns when offering filters.
I will try and figure out a way to get around it. (it is quite annoying)
